<?php

/**
 * @file
 * Primary module hooks for Example mail module.
 */
use Drupal\Core\Mail\MailFormatHelper;


 /**
 * Implements hook_mail().
 */
function example_mail_mail($key, &$message, $params) {
  switch ($key) {
    case 'example_mail_test':
      $message['from'] = $params['from'];
      $message['headers']['From'] = "WACHS <{$params['from']}>";
      $message['headers']['Sender'] = $message['headers']['Return-Path'] = $message['from'];

      $message['headers']['Reply-To'] = $params['from'];
      $message['subject'] = $params['subject'];
      // $message['headers']['Cc'] = $params['cc'];
      $message['format'] = 'text/html';
      $message['body'][] = $params['message'];
      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed';
      $message['headers']['MIME-Version'] = '1.0';
      break;
  }
  
}

/**
 * Implements hook_entity_access().
 */
function example_mail_entity_access(\Drupal\Core\Entity\EntityInterface $entity, $operation, \Drupal\Core\Session\AccountInterface $account) {
  if ($entity->getEntityTypeId() == 'paragraph') {
    if ($operation == 'view') {
      // Get the current language.
      $current_language = \Drupal::languageManager()->getCurrentLanguage()->getId();

      // Check if the paragraph has a translation in the current language.
      if ($entity->hasTranslation($current_language)) {
        // Get the translation.
        $translation = $entity->getTranslation($current_language);

        // Check if the translation is not published.
        if (!$translation->isPublished()) {
          return \Drupal\Core\Access\AccessResult::forbiddenIf(!$account->hasPermission("view unpublished paragraphs"));
        }
      }
    }
  }
  return \Drupal\Core\Access\AccessResult::neutral();
}